In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_csv('../data/data.csv')
df.head()

,day,month,totalPoints,cumulativePoints,rollingAvgPoints,taskCompleted,taskMissed,pointsGain,pointsDeduct,mindStatus
0,8,4,12,12,0.000000,1,0,12,0,Default
1,1,5,10,22,0.000000,2,1,20,10,Default
2,2,7,25,47,15.666667,3,2,35,10,Default
3,3,6,-10,37,8.333333,2,2,15,25,Default
4,4,6,-28,9,-4.333333,1,1,2,30,Default

In [6]:
df.describe()

,day,month,totalPoints,cumulativePoints,rollingAvgPoints,taskCompleted,taskMissed,pointsGain,pointsDeduct
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000
mean,9.297710,6.290076,11.702290,500.679389,11.399491,3.572519,1.038168,28.763359,17.061069
std,8.343302,3.429484,31.632917,459.015104,26.795918,1.762998,1.025855,17.195184,19.873351
min,1.000000,1.000000,-85.000000,-244.000000,-77.666667,0.000000,0.000000,0.000000,0.000000
25%,3.000000,3.000000,-6.000000,64.000000,-3.000000,2.000000,0.000000,15.000000,0.000000
50%,6.000000,6.000000,14.000000,578.000000,17.000000,4.000000,1.000000,27.000000,10.000000
75%,14.000000,9.000000,35.000000,763.500000,32.666667,5.000000,1.000000,42.000000,30.000000
max,30.000000,12.000000,64.000000,1533.000000,53.666667,6.000000,4.000000,67.000000,100.000000

In [7]:
df.isnull().sum()

day                 0
month               0
totalPoints         0
cumulativePoints    0
rollingAvgPoints    0
taskCompleted       0
taskMissed          0
pointsGain          0
pointsDeduct        0
mindStatus          0
dtype: int64

In [9]:
(df == '?').sum()

day                 0
month               0
totalPoints         0
cumulativePoints    0
rollingAvgPoints    0
taskCompleted       0
taskMissed          0
pointsGain          0
pointsDeduct        0
mindStatus          0
dtype: int64

In [27]:
df['mindStatus'] = df['mindStatus'].astype('category')

label_mapping = dict(enumerate(df['mindStatus'].cat.categories))
label_mapping

{0: 'Default',
 1: 'Distracted',
 2: 'Focused',
 3: 'Motivated',
 4: 'Stressed',
 5: 'Tired'}

In [30]:
df['mindStatus'] = df['mindStatus'].cat.codes
df

,day,month,totalPoints,cumulativePoints,rollingAvgPoints,taskCompleted,taskMissed,pointsGain,pointsDeduct,mindStatus
0,8,4,12,12,0.000000,1,0,12,0,0
1,1,5,10,22,0.000000,2,1,20,10,0
2,2,7,25,47,15.666667,3,2,35,10,0
3,3,6,-10,37,8.333333,2,2,15,25,0
4,4,6,-28,9,-4.333333,1,1,2,30,0
...,...,...,...,...,...,...,...,...,...,...
126,26,2,30,1401,31.333333,4,1,40,10,2
127,27,9,27,1428,36.333333,4,0,27,0,2
128,28,1,45,1473,34.000000,5,1,50,5,2
129,29,8,35,1508,35.666667,4,0,35,0,2
130,30,1,25,1533,35.000000,4,1,35,10,2

In [32]:
features = df.drop(columns=['mindStatus'], axis=1)
labels = df['mindStatus']

In [34]:
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [42]:
processed_df = pd.DataFrame(features_scaled, columns=features.columns)
processed_df['mindStatus'] = labels
processed_df.head()

,day,month,totalPoints,cumulativePoints,rollingAvgPoints,taskCompleted,taskMissed,pointsGain,pointsDeduct,mindStatus
0,-0.156136,-0.670325,0.009448,-1.068713,-0.427052,-1.464774,-1.015888,-0.978629,-0.861785,0
1,-0.998353,-0.377616,-0.054020,-1.046843,-0.427052,-0.895381,-0.037349,-0.511597,-0.356667,0
2,-0.878037,0.207801,0.421989,-0.992170,0.159859,-0.325988,0.941190,0.364089,-0.356667,0
3,-0.757720,-0.084908,-0.688700,-1.014039,-0.114866,-0.895381,0.941190,-0.803492,0.401010,0
4,-0.637403,-0.084908,-1.259912,-1.075274,-0.589389,-1.464774,-0.037349,-1.562420,0.653569,0

In [43]:
processed_df.to_csv('../data/processed_data.csv', index=False)
print("Processed data saved to 'processed_training_data.csv'")

Processed data saved to 'processed_training_data.csv'